### ISSUE TITLE
Build and test automation through Cabal & Travis

### ISSUE THREAD

**Issue by allegroCoder** [tuura/scenco#11]
1. Automating build and test phase using cabal and travis.

2. Implementing some test functions in the main.

Useful links for examples on how to use these tools can be found on:
- https://github.com/tuura/concepts
- shaking up GHC (adding compilation options for c++ sid

**Comment by allegroCoder** [comment]
I managed to automate compilation and building with travis. Though, I am facing with some compilation problems, probably related to the fact that I am using `ghc 7.8` rather than the latest version not available on travis!

**Comment by snowleopard** [comment]
@allegroCoder Yes, I believe we are relying on `ghc 7.10`, for example we are using `traverse`.

I suggest you follow the example in https://github.com/snowleopard/shaking-up-ghc/blob/master/.travis.yml. We install `ghc-7.10.3` there (we probably don't need any other packages in our case).

It may be a good idea to do tests both on `Linux` and `Mac OS X`, because we are using FFI and I expect some things may break on different platforms. Also, once Travis integration is complete we should also think about setting up AppVeyor CI on Windows: https://github.com/snowleopard/shaking-up-ghc/blob/master/.appveyor.yml.

**Comment by allegroCoder** [comment]
Just managed to install ghc 7.10 and run the test on travis setting Linux environment.

Before pulling the request, I'll try to see if it works for Mac OS X as well.

**Comment by snowleopard** [comment]
:+1:

**Comment by allegroCoder** [comment]
`Linux` and `Mac OS X` work both.

**Comment by snowleopard** [comment]
@allegroCoder Now it's time to add testing on Windows using AppVeyor. Can you try to do that? As before, you can start with Shaking-up-GHC script as an example.

**Comment by snowleopard** [comment]
Note: at the moment tests fail on my Windows machine.

**Comment by allegroCoder** [comment]
First attempt to add testing on Windows.
I put into the root folder the file `.appveyor.yml` which contains:

```
ghc: 7.10.3

script:
    - cabal configure --enable-tests
    - cabal build
    - cabal test --show-details=always
```

and the standard file `scenco.cabal`
```
name:          scenco
version:       0.0.1
synopsis:      A collection of encoding algorithms for conditional graphs
license:       BSD3
license-file:  LICENSE
author:        Tuura authors (see AUTHORS file)
maintainer:    Alessandro de Gennaro <a.de-gennaro@ncl.ac.uk>, github: @allegroCoder
copyright:     Tuura authors (see AUTHORS file), 2015
homepage:      https://github.com/tuura/scenco
category:      Algorithms
build-type:    Simple
cabal-version: >=1.10

extra-source-files:
    src/c++/base.h
    src/c++/*.cpp

source-repository head
    type:     git
    location: https://github.com/tuura/scenco.git

library
    hs-source-dirs:   src
    exposed-modules:
        Tuura.Code
        Tuura.Encode
        Tuura.Synthesis
        Tuura.TechnologyMapping
    other-modules:
        Tuura.Circuit
        Tuura.Formula
        Tuura.Graph
        Tuura.Library
    c-sources:        src/c++/scenco.cpp
    include-dirs:     src/c++
    build-depends:    base >= 4.7 && < 5
                    , mtl == 2.2.*
                    , transformers >= 0.4 && < 0.6
                    , filepath
    default-language: Haskell2010
    other-extensions: TypeFamilies
    GHC-options:      -Wall -fwarn-tabs
    extra-libraries:  stdc++

test-suite scenco-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    build-depends:    base >= 4.7 && < 5
                    , filepath
                    , scenco
    other-extensions: TypeFamilies
    default-language: Haskell2010
    GHC-options:      -Wall -fwarn-tabs
    extra-libraries:  stdc++
```

Question:
appVeyor is supposed to test code in windows environment. So should I create another file with "\" rather than "/"? If so, how could I tell through `.appveyor.yml` to use this particolar file?

Error generated
```
Build started
git clone -q --branch=master https://github.com/allegroCoder/scenco-1.git C:\projects\scenco-1
git checkout -qf 42846ae1ad84c1795464bc2802e10bca18b49c92
Specify a project or solution file. The directory does not contain a project or solution file.
```

**Comment by snowleopard** [comment]
I think the error is because the file name `.appveyor.yml` is not standard. By default AppVeyor uses `appveyor.yml` (without dot), but I prefer the non-standard one for consistency with Travis. You can set up the correct name in your AppVeyor settings.

**Comment by snowleopard** [comment]
I don't think you should worry about slashes. Forward slashes should work in cabal across platforms.

**Comment by allegroCoder** [comment]
this code:
```
install:
    - cabal install --only-dependencies

build_script:
    - cabal configure --enable-tests
    - cabal build
    - cabal test --show-details=always
```
generate following output in appveyor:
```
Build started
git clone -q --branch=master https://github.com/allegroCoder/scenco-1.git C:\projects\scenco-1
git checkout -qf 92222827d45c135bb2f636695ad86adc05c9581b
Running Install scripts
cabal install --only-dependencies
'cabal' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

I guess that I need to install cabal before proceeding. Do you know how to do that, I am trying to take pieces of code from the `appveyor.yml` in shake-ghc, but did not manage to do it yet.

**Comment by snowleopard** [comment]
A quick google search brings me here: https://github.com/elm-lang/elm-platform/blob/14a6e51fd7d39f5f5962c95312aea66b8a7cdf1a/appveyor.yml

In particular:
```
  - curl -s -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz > nul
  - 7z x cabal.tar -ocabal_installation > nul
  - cd cabal_installation
  - ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe
  - set PATH=%PATH%;c:\projects\elm-platform\cabal_installation
  - cabal --version
```

**Comment by allegroCoder** [comment]
```
clone_folder: c:\projects\scenco-platform

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cd c:\projects\scenco-platform
  - curl -s -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz > nul
  - 7z x cabal.tar -ocabal_installation > nul
  - cd cabal_installation
  - ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe
  - set PATH=%PATH%;c:\projects\scenco-platform\cabal_installation
  - cabal --version
  - cd c:\projects\scenco-platform
  - curl -s -oghc.tar.xz -L https://www.haskell.org/ghc/dist/7.10.3/ghc-7.10.3-i386-unknown-mingw32.tar.xz  
  - 7z x ghc.tar.xz > nul
  - 7z x ghc.tar > nul
  - set PATH=%PATH%;c:\projects\scenco-platform\ghc-7.10.3\bin
  - ghc --version
  - runhaskell --version

build_script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test --show-details=always
```

generate following error on AppVeyor:

```
cabal configure --enable-tests
Config file path source is default config file.
Config file C:\Users\appveyor\AppData\Roaming\cabal\config not found.
Writing default configuration to
C:\Users\appveyor\AppData\Roaming\cabal\config
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Configuring scenco-0.0.1...
cabal: At least the following dependencies are missing:
mtl ==2.2.*
Command exited with code 1
```

I have tried installing that particular dependency following different tutorials, did not manage to make them work yet. 

References: 
- [LINK 1](https://github.com/haskell/cabal/issues/1285)
- [How to install cabal](https://www.schoolofhaskell.com/user/simonmichael/how-to-cabal-install#reset)

Still working on this! :+1:

**Comment by allegroCoder** [comment]
Seems I have sorted the issue not going through cabal. Simply compiling code via YAML script. I'll keep issue updated.

**Comment by snowleopard** [comment]
```
cabal: At least the following dependencies are missing:
mtl ==2.2.*
```
This one should be easy to fix. You need to add the following step to the `install` script:
```
    - cabal install --only-dependencies
```
This makes sure all required Haskell packages, such as `mtl` are installed.

**Comment by allegroCoder** [comment]
`cabal install --only-dependencies` generates following error:

```
Config file path source is default config file.
Config file C:\Users\appveyor\AppData\Roaming\cabal\config not found.
Writing default configuration to
C:\Users\appveyor\AppData\Roaming\cabal\config
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: scenco-0.0.1 (user goal)
next goal: mtl (dependency of scenco-0.0.1)
Dependency tree exhaustively searched.
Command exited with code 1
```

Hence, I tried to insert `cabal update` before installing the dependencies but that's the following error:

```
Config file path source is default config file.
Config file C:\Users\appveyor\AppData\Roaming\cabal\config not found.
Writing default configuration to
C:\Users\appveyor\AppData\Roaming\cabal\config
Downloading the latest package list from hackage.haskell.org
Command exited with code 1073807366
```

I also tried to do the following
```
clone_folder: c:\projects\scenco-platform

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cd c:\projects\scenco-platform
  - curl -s -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz > nul
  - 7z x cabal.tar -ocabal_installation > nul
  - cd cabal_installation
  - ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe
  - set PATH=%PATH%;c:\projects\scenco-platform\cabal_installation
  - cabal --version
  - cd c:\projects\scenco-platform
  - curl -s -oghc.tar.xz -L https://www.haskell.org/ghc/dist/7.10.3/ghc-7.10.3-i386-unknown-mingw32.tar.xz  
  - 7z x ghc.tar.xz > nul
  - 7z x ghc.tar > nul
  - set PATH=%PATH%;c:\projects\scenco-platform\ghc-7.10.3\bin
  - ghc --version
  - runhaskell --version

build_script:
  - cd c:\projects\scenco-platform\
  - ghc --make Main.hs -i:src/ -lstdc++ src/c++/scenco.cpp -o scenco.exe
  - scenco.exe
```

Unfortunately the flow stops at the very last statement. `scenco.exe` does not do anything, so I assume this approach not to be correct either.

**Comment by snowleopard** [comment]
I think you should replace `build_script` with the following (same as in `concepts`):
```
  - cd c:\projects\scenco-platform\
  - cabal configure --enable-tests
  - cabal build
  - cabal test --show-details=always
```

**Comment by allegroCoder** [comment]
Should I try this:
```
clone_folder: c:\projects\scenco-platform

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cd c:\projects\scenco-platform
  - curl -s -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz > nul
  - 7z x cabal.tar -ocabal_installation > nul
  - cd cabal_installation
  - ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe
  - set PATH=%PATH%;c:\projects\scenco-platform\cabal_installation
  - cabal --version
  - cd c:\projects\scenco-platform
  - curl -s -oghc.tar.xz -L https://www.haskell.org/ghc/dist/7.10.3/ghc-7.10.3-i386-unknown-mingw32.tar.xz  
  - 7z x ghc.tar.xz > nul
  - 7z x ghc.tar > nul
  - set PATH=%PATH%;c:\projects\scenco-platform\ghc-7.10.3\bin
  - ghc --version
  - runhaskell --version
# - cabal update 
  - cabal install --only-dependencies

build_script:
  - cd c:\projects\scenco-platform\
  - cabal configure --enable-tests
  - cabal build
  - cabal test --show-details=always
```
